Page({
  data:{
    viewData:[
      {
        title:"List列表",
        page:"/pages/extra/view/list/index"
      },
      {
        title:"Tabs选项卡",
        page:"/pages/extra/view/tabs/index"
      },
      {
        title:"Card卡片",
        page:"/pages/extra/view/card/index"
      },
      {
        title:"Grid宫格",
        page:"/pages/extra/view/grid/index"
      },
      {
        title:"steps步骤条",
        page:"/pages/extra/view/steps/index"
      },
      {
        title:"footer页脚",
        page:"/pages/extra/view/footer/index"
      },
      {
        title:"flex布局",
        page:"/pages/extra/view/flex/index"
      },
      {
        title:"pagination分页",
        page:"/pages/extra/view/pagination/index"
      },
      {
        title:"collapse折叠面板",
        page:"/pages/etra/view/collapse/index"
      }
    ]
  }
})